esphome:
  name: bno055_test
  friendly_name: BNO055 Test

esp32:
  board: esp32dev
  framework:
    version: latest

i2c:
  sda: 21
  scl: 22
  frequency: 400kHz

sensor:
  - platform: bno055
    i2c_id: i2c_bus
    address: 0x28
    update_interval: 50ms  # Fréquence réglable: 10ms, 50ms, 100ms, 200ms, 500ms, 1s
    
    # Accelerometer
    accel_x:
      name: "Accelerometer X"
      unit_of_measurement: "m/s²"
    accel_y:
      name: "Accelerometer Y" 
      unit_of_measurement: "m/s²"
    accel_z:
      name: "Accelerometer Z"
      unit_of_measurement: "m/s²"
      
    # Gyroscope
    gyro_x:
      name: "Gyroscope X"
      unit_of_measurement: "°/s"
    gyro_y:
      name: "Gyroscope Y"
      unit_of_measurement: "°/s"
    gyro_z:
      name: "Gyroscope Z"
      unit_of_measurement: "°/s"
      
    # Magnetometer
    mag_x:
      name: "Magnetometer X"
      unit_of_measurement: "μT"
    mag_y:
      name: "Magnetometer Y"
      unit_of_measurement: "μT"
    mag_z:
      name: "Magnetometer Z"
      unit_of_measurement: "μT"
      
    # Euler angles
    euler_h:
      name: "Euler Heading"
      unit_of_measurement: "°"
    euler_r:
      name: "Euler Roll"
      unit_of_measurement: "°"
    euler_p:
      name: "Euler Pitch"
      unit_of_measurement: "°"
      
    # Linear acceleration
    linear_accel_x:
      name: "Linear Acceleration X"
      unit_of_measurement: "m/s²"
    linear_accel_y:
      name: "Linear Acceleration Y"
      unit_of_measurement: "m/s²"
    linear_accel_z:
      name: "Linear Acceleration Z"
      unit_of_measurement: "m/s²"
      
    # Gravity
    gravity_x:
      name: "Gravity X"
      unit_of_measurement: "m/s²"
    gravity_y:
      name: "Gravity Y"
      unit_of_measurement: "m/s²"
    gravity_z:
      name: "Gravity Z"
      unit_of_measurement: "m/s²"
      
    # Temperature
    temperature:
      name: "Temperature"
      unit_of_measurement: "°C"
      
    # Compass (Magnetic North)
    compass:
      name: "Compass Heading"
      unit_of_measurement: "°"
      accuracy_decimals: 1 